### ISSUE TITLE
Pre-Trained Model

### ISSUE THREAD

**Issue by usamasadiq706** [squareRoot3/Rethinking-Anomaly-Detection#10]
Hi. I am using your source code. I was wondering would it be possible if you can provide your pre-trained models for BWGNN (Homogeneous or Heterogeneous).

**Comment by squareRoot3** [comment]
Hello! The current version of the code does not consider functionality for saving and loading model weights. Additionally, the training time is short except for T-Social. Therefore, it is recommended to train the model on your own.

**Comment by squareRoot3** [comment]
You can also take a look at my new project, GADBench, which evaluated BWGNN on more datasets.

**Comment by usamasadiq706** [comment]
Okay thanks for you response. I will train the BWGNN model. I have seen the Graph anomaly detection benchmark project. This benchmark was much needed, I am looking forward employ it as well.
