### ISSUE TITLE
Why band-pass filter can alleivate the "right shift" effect due to graph anomalies in the first place?

### ISSUE THREAD

**Issue by jingweio** [squareRoot3/Rethinking-Anomaly-Detection#11]
Hi, I would like to first express my appreciation for the theoretical analysis presented in the first half of your paper. Your work from a spectral perspective provides a insightful quantification of the impact of anomalies on a clean graph. 

However, moving on to the latter part of the paper, I find myself somewhat uncertain about a few aspects. While I understand how beta kernels shift from left to right to capture high-frequency information, the mechanics of how a band-pass filter counters the "right shift" effect due to graph anomalies remains unclear to me. 

Why did you choose a band-pass filter as your preferred option? Is it because it can effectively capture the nuances between low and high-frequency information by easily shifting towards either the left or right sides? Could you kindly elaborate on the motivation and thought process behind your model's design in this regard?

**Comment by squareRoot3** [comment]
> Is it because it can effectively capture the nuances between low and high-frequency information by easily shifting towards either the left or right sides?

Yes.
