### ISSUE TITLE
May you share how to plot the spectral analysis in the paper

### ISSUE THREAD

**Issue by CurryTang** [squareRoot3/Rethinking-Anomaly-Detection#2]
Thanks for your wonderful work. May you share how to plot the spectral analysis graph in the paper (such as Figure 1 and Figure 2)?

**Comment by squareRoot3** [comment]
Thank you for your interest! I have uploaded it to google drive and you can find it in readme.md

**Comment by CurryTang** [comment]
Many Thanks!
