### ISSUE TITLE
Graph Fourier transform of node attributes

### ISSUE THREAD

**Issue by luisfredgs** [squareRoot3/Rethinking-Anomaly-Detection#3]
Hello. Thank you for sharing your work with us. I have a doubt. According to the paper, you analyze anomalies via the lens of the graph spectrum (i.e., after the graph Fourier transform of node attributes). Conversely, I did not find where such transform occurs in the source code. Could you help me? With regards.

**Comment by squareRoot3** [comment]
Hi! Our code for plotting Figures 1 and 2 is related to the analysis of the graph spectrum in section 2, which you can find in readme. This repo mainly contains the implementation of BWGNN in section 3.

For large-scale real-world datasets, performing spectral decomposition/graph Fourier transform is extremely time-consuming as it is O(node^3) in time complexity, so we did not do that. Instead, as BWGNN has polynomial spectral filters, we can use the same fast computation technique as ChebyNet, GPR-GNN, etc., to avoid explicit spectral decomposition. The time complexity is only O(edge) and thus we can support large-scale graphs. For a better understanding, please refer to section 3 in our paper and other related spectral GNN (e.g., https://docs.dgl.ai/generated/dgl.nn.pytorch.conv.ChebConv.html?highlight=chebconv#dgl.nn.pytorch.conv.ChebConv).

**Comment by luisfredgs** [comment]
Hello, thanks for your reply. You cleared my doubts :-).
