### ISSUE TITLE
May you share how to plot the Figure 3 in the paper ?

### ISSUE THREAD

**Issue by GavinYGM** [squareRoot3/Rethinking-Anomaly-Detection#5]
Thanks a lot!

**Comment by squareRoot3** [comment]
Unfortunately, I am unable to find the original code for this figure. A similar code is attached for reference. First run utils.py and then run plot_figure3.py.
[figure3.zip](https://github.com/squareRoot3/Rethinking-Anomaly-Detection/files/10705469/figure3.zip)

**Comment by GavinYGM** [comment]
Thanks for your reply!
