### ISSUE TITLE
Problem regarding your research paper

### ISSUE THREAD

**Issue by cankaili121** [squareRoot3/Rethinking-Anomaly-Detection#6]
Dear Tang,

I am writing to express my appreciation for the work that you and your team have done on your recent research paper. However, after reading the paper, I was unable to find a clear research **"problem"**. While I found your **“observations”** regarding the phenomenon of right-shifted spectral energy to be thorough and well-explained, I am confused as to what **”problems“** this phenomenon can cause. Does the right-shifted spectral energy lead to a decrease in anomaly detection accuracy? The paper does not seem to provide a clear illustration or explanation.

Additionally, I am curious about the necessity of the spectral graph convolutional network that you designed. Is it necessary for solving the research **"problem"**? I would appreciate any insights or explanations that you can provide on this matter.

Thank you for your time and effort in conducting this research.

**Comment by sqc-cser** [comment]
if you are a Chinese, I will recommend you to watch his video about this.
https://www.bilibili.com/video/BV1BG411p7og/

**Comment by squareRoot3** [comment]
Thanks for the response of sqc-cser.
We also have a short English talk in https://slideslive.com/38984068/rethinking-graph-neural-networks-for-anomaly-detection?ref=speaker-24150
I think our paper and talk have clearly addressed your question.
