### ISSUE TITLE
Problem on loading data in batch mode

### ISSUE THREAD

**Issue by blackboxo** [squareRoot3/Rethinking-Anomaly-Detection#7]
I noticed that you have given the code of conv for batch mode, but how to load data in batch mode for training? Could you please give the code for this part? Thanks!

**Comment by squareRoot3** [comment]
I apologize that the batch mode is duplicated and I do not have the code currently. 
I will add this mode to my next project probably next month. Please stay tuned. You can also read DGL's official document about mini-batch sampling and add that by yourself.

**Comment by blackboxo** [comment]
Thanks for your reply. DGL provides mini-batch sampling for spatial GNNs, is it able to use in spectral GNNs like BWGNN? For example, if using MultiLayerFullNeighborSampler for sampling data, is it correct that I sample d+1 layers for BWGNN with order d?

**Comment by squareRoot3** [comment]
Yes, BWGNN can be considered as d-hop spatial GNNs. I think it will work.  But I have not tried yet.

**Comment by blackboxo** [comment]
Thanks! I will try it.
