### ISSUE TITLE
Potential repeated edges caused by "dgl.to_homogeneous()"

### ISSUE THREAD

**Issue by jingweio** [squareRoot3/Rethinking-Anomaly-Detection#9]
Hi, thank you very much for your wonderful work. However, I noticed a small bug in your code on lines 52 and 58 of dataset.py. I found that the use of dgl.to_homogeneous() here might lead to repeated graph edges in the new graph. 

Below is my verification code, and the printed result is False:

```
from dgl.data import FraudYelpDataset
import torch
import dgl

dataset = FraudYelpDataset()
graph = dataset[0]
graph = dgl.to_homogeneous(graph, ndata=['feature', 'label', 'train_mask', 'val_mask', 'test_mask'])
edge_index = torch.stack(graph.edges(), dim=0)
print(torch.unique(edge_index.T, dim=0).shape == edge_index.T.shape)
```
Thanks for your time~

**Comment by squareRoot3** [comment]
You are correct. But interestingly, after removing duplicated edges, the performance of BWGNN on Amazon slightly decreased. It seems that these repeated edges can provide some useful additional information.

40% training after removing duplicated edges: MF1-mean: 91.95, MF1-std: 0.69, AUC-mean: 97.53, AUC-std: 0.41

**Comment by jingweio** [comment]
Thanks for your response~
